# Generated by Django 4.1.3 on 2022-12-02 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id_upload', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='images/')),
                ('nome', models.CharField(max_length=255)),
                ('user', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=16)),
                ('senha', models.CharField(max_length=16)),
                ('email', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Mockup',
            fields=[
                ('id_mockup', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('cor', models.CharField(max_length=255)),
                ('vermelho', models.CharField(max_length=255, null=True)),
                ('verde', models.CharField(max_length=255, null=True)),
                ('azul', models.CharField(max_length=255, null=True)),
                ('user', models.IntegerField(blank=True, null=True)),
                ('imagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TCCApp.upload')),
            ],
        ),
    ]
